### PR TITLE
Add Steamoji

### PR DESCRIPTION
**Pull request by jordanbuchman**
Adds a link to a list of emojipacks of all Steam emoticons by game.

### CODE REVIEW

**Comment by zachfeldman** [comment]
Cool @jordanbuchman and have you tested this specific YAML file with emojipacks?

**Comment by jordanbuchman** [comment]
Not all of them, but I've used a few. They were all generated by the same
program.

On May 23, 2017 2:04 PM, "Zach Feldman" <notifications@github.com> wrote:

Cool @jordanbuchman <https://github.com/jordanbuchman> and have you tested
this specific YAML file with emojipacks?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lambtron/emojipacks/pull/113#issuecomment-303515828>,
or mute the thread

**Comment by zachfeldman** [comment]
Ok @jordanbuchman - all linked to emojipacks need to be tested with this plugin before being merged - please let me know once this pack has been tested and I'm glad to merge!

**Comment by zachfeldman** [comment]
@jordanbuchman do you have time to test this emojipack? Otherwise I will close the PR next week if there's no further activity. Thanks for taking the time either way!

**Pull request closed without merging**
