### PR TITLE
add luckyparrot and rotatingparrot

### PR DESCRIPTION
**Pull request by snoek09**
Added 2 new parrots:

- luckyparrot 
- rotatingparrot

### CODE REVIEW

**Comment by snoek09** [comment]
Parrot party pack passes (PPPP): https://travis-ci.org/lambtron/emojipacks/builds/285425499#L2146

**Comment by hugovk** [comment]
CI failure was in another pack (packs/hipchat.yaml):

https://travis-ci.org/lambtron/emojipacks/builds/285425499#L831

**Comment by zachfeldman** [comment]
Thanks @hugovk 🙌

**Comment by zachfeldman** [comment]
And @snoek09 for the Parrot PR

**Pull request merged**
