### PR TITLE
Added college football logos emojis for each school in the SEC

### PR DESCRIPTION
**Pull request by kvalade**
Added logos for:
- florida
- georgia
- kentucky
- missouri
- south carolina
- tennessee
- vanderbilt
- alabama
- arkansas
- auburn
- louisiana state
- ole miss
- mississippi state
- texas a&m

### CODE REVIEW

**Comment by hugovk** [comment]
@kvalade Slack doesn't allow spaces in emoji names:

> Custom emoji names can only contain lower case letters, numbers, dashes and underscores

**Comment by hugovk** [comment]
See PR https://github.com/kvalade/emojipacks/pull/1.

**Comment by zachfeldman** [comment]
@kvalade please make the above edits if you get a chance or I'll close this PR, sorry for the delay.. Thanks for your contribution!

**Comment by zachfeldman** [comment]
Hey there @kvalade   , I'm closing this PR for now but feel free to open it back up later on if you'd like if it's still relevant!

**Pull request closed without merging**
