### PR TITLE
created an all emoji file

### PR DESCRIPTION
**Pull request by jenniferabowd**
I created a file with all the emojis offered by Emojipack.

### CODE REVIEW

**Comment by zachfeldman** [comment]
Woah, going for it! I like it. Did you test it with a Slack instance with no errors? If so, I will merge.

**Comment by jenniferabowd** [comment]
Hi Zach,

Yes I tested it and did not get any errors. It takes a half hour to run. Thank you for creating this great project!

Best,

Jennifer Kaplan

**Comment by zachfeldman** [comment]
You may thank the mighty @lambtron I am but a humble maintainer. Haha. Consider yourself merged

**Comment by zachfeldman** [comment]
@jenkaplan sorry but I had to revert your commit because it broke the build :(

https://travis-ci.org/lambtron/emojipacks/builds/242672946?utm_source=email&utm_medium=notification

I still think it's a good idea to do this, however, it might make a little more sense to implement code that joins multiple emoji files so people can make their own multipacks, vs pushing a big multipack with all the emojipacks that exist already, which we'd probably have to update. Maybe something that adds a flag to the emojipacks command to include multiple packs (I don't think you can do this already).

Thanks for your contribution either way!

**Comment by jenniferabowd** [comment]
Hi Zach,

I’m so sorry it broke the build! This was my first attempt at contributing to open source. Thank you for being so kind and making suggestions.

Best,

Jen

**Comment by zachfeldman** [comment]
No problem!

**Comment by lambtron** [comment]
This is literally everything.

Thank you @jenkaplan!!

**Comment by jenniferabowd** [comment]
@lambtron No problem! I'm sorry that this broke your npm build!

**Pull request merged**
