### PR TITLE
Trying to add 2fa support.

### PR DESCRIPTION
**Pull request by zachfeldman**
So, this would theoretically work, but I keep getting ">Too many login failures!" error. Maybe because I tried to test this about 100 times when I first wrote it, but I'm even getting this a few days later.

Thought I would PR it in case anyone has suggestions for getting it to work.

### CODE REVIEW

**Comment by randomcamel** [comment]
This does seem to work, but still fails to get the upload crumb:

> Logged in
Upload crumb is undefined
Uh oh! Error: Login error: could not get emoji upload crumb for https://hashicorp.slack.com

Darned if I can figure out why, since the CSS selector works in Chrome, but debugging it may be beyond my current JS skills.

**Comment by zachfeldman** [comment]
@randomcamel are you saying that the emojis are actually being added in your case?

Yeah I couldn't figure it out either.

**Comment by randomcamel** [comment]
@zachfeldman No, but as far as I could tell the login was successful, and it was just the parsing the crumb out of the HTML that failed.

It looks like Slack terminates the upload crumb with `-☃`, so it seems plausible that something in the code is not handling the emoji gracefully. (It further seems plausible that Slack does that just to prevent stuff like this from working.)

**Comment by zachfeldman** [comment]
Finally had time to get back to this! 2FA is working and this PR is ready to merge, pending approval.

**Comment by zachfeldman** [comment]
@randomcamel the login was mostly successful but I didn't write the form parsing code correctly, I was testing using jQuery but the lib uses cheer-io. Made some changes to the way I was parsing form data and it works now!

**Comment by lambtron** [comment]
LGTM!! Thank you!!!

**Pull request merged**
